# application: php-gds-demo
# version: alpha2
runtime: php55
api_version: 1
# threadsafe: true

handlers:

# Application static resources

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /img
  static_dir: public/img

- url: /fonts
  static_dir: public/fonts

# Form handler

- url: /post.php
  script: public/post.php

- url: /sign.php
  script: public/sign.php

# Protected handler
- url: /index.php
  script: private/index.php

# Default handler
- url: /
  script: public/main.php

#Connexion handler
- url: /login
  script: public/login.php

# Deconnexion handler
- url: /deconnexion
  script: private/deconnexion.php

# CO2, CO and NH3 handler
- url: /index.php/co2
  script: private/co2.php

- url: /index.php/co
  script: private/co.php

- url: /index.php/nh3
  script: private/nh3.php