application: php-gds-demo
version: alpha
runtime: php
api_version: 1
threadsafe: yes

handlers:

# Application static resources

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /img
  static_dir: public/img

- url: /fonts
  static_dir: public/fonts

# Form handler

- url: /post.php
  script: public/post.php

# Default handler

- url: .*
  script: public/main.php
